#! /bin/sh
#
# System startup script for the setup reset (network boot default) script
#
### BEGIN INIT INFO
# Provides: setup-reset
# Required-Start: xinetd
# Should-Start:   orthos
# Required-Stop:
# Should-Stop:
# Default-Start:  3 5
# Default-Stop:   0 1 2 6
# Short-Description: Start to listen on tftp logs
### END INIT INFO

# Source SuSE config
. /etc/rc.status

case $1 in
    start)
        trap "" 1
        /srv/tftpboot/grub2/scripts/setup-reset.py  &
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        rc_status
        ;;
    stop)
        killall setup-reset.py
        ;;
    *)
        echo "Usage: /sbin/rcsetup-reset {start|stop}"
        exit 1
        ;;
esac
